/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTempoRouteImport } from './routes/_authenticated/tempo'
import { Route as AuthenticatedSocialSellingRouteImport } from './routes/_authenticated/social-selling'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedFunisRouteImport } from './routes/_authenticated/funis'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedCicloRouteImport } from './routes/_authenticated/ciclo'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedAcoesRouteImport } from './routes/_authenticated/acoes'
import { Route as AuthenticatedAtividadesIndexRouteImport } from './routes/_authenticated/atividades.index'
import { Route as AuthenticatedAtividadesTiposRouteImport } from './routes/_authenticated/atividades.tipos'
import { Route as AuthenticatedAtividadesSemanasRouteImport } from './routes/_authenticated/atividades.semanas'
import { Route as AuthenticatedAtividadesIntencoesRouteImport } from './routes/_authenticated/atividades.intencoes'
import { Route as AuthenticatedAtividadesAgendaRouteImport } from './routes/_authenticated/atividades.agenda'
import { Route as AuthenticatedAtividadesProjetoIdRouteImport } from './routes/_authenticated/atividades.projeto.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTempoRoute = AuthenticatedTempoRouteImport.update({
  id: '/tempo',
  path: '/tempo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialSellingRoute =
  AuthenticatedSocialSellingRouteImport.update({
    id: '/social-selling',
    path: '/social-selling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunisRoute = AuthenticatedFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCicloRoute = AuthenticatedCicloRouteImport.update({
  id: '/ciclo',
  path: '/ciclo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcoesRoute = AuthenticatedAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesIndexRoute =
  AuthenticatedAtividadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAtividadesTiposRoute =
  AuthenticatedAtividadesTiposRouteImport.update({
    id: '/tipos',
    path: '/tipos',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAtividadesSemanasRoute =
  AuthenticatedAtividadesSemanasRouteImport.update({
    id: '/semanas',
    path: '/semanas',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAtividadesIntencoesRoute =
  AuthenticatedAtividadesIntencoesRouteImport.update({
    id: '/intencoes',
    path: '/intencoes',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAtividadesAgendaRoute =
  AuthenticatedAtividadesAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)
const AuthenticatedAtividadesProjetoIdRoute =
  AuthenticatedAtividadesProjetoIdRouteImport.update({
    id: '/projeto/$id',
    path: '/projeto/$id',
    getParentRoute: () => AuthenticatedAtividadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/atividades': typeof AuthenticatedAtividadesRouteWithChildren
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo': typeof AuthenticatedCicloRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social-selling': typeof AuthenticatedSocialSellingRoute
  '/tempo': typeof AuthenticatedTempoRoute
  '/atividades/agenda': typeof AuthenticatedAtividadesAgendaRoute
  '/atividades/intencoes': typeof AuthenticatedAtividadesIntencoesRoute
  '/atividades/semanas': typeof AuthenticatedAtividadesSemanasRoute
  '/atividades/tipos': typeof AuthenticatedAtividadesTiposRoute
  '/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/atividades/projeto/$id': typeof AuthenticatedAtividadesProjetoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo': typeof AuthenticatedCicloRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social-selling': typeof AuthenticatedSocialSellingRoute
  '/tempo': typeof AuthenticatedTempoRoute
  '/atividades/agenda': typeof AuthenticatedAtividadesAgendaRoute
  '/atividades/intencoes': typeof AuthenticatedAtividadesIntencoesRoute
  '/atividades/semanas': typeof AuthenticatedAtividadesSemanasRoute
  '/atividades/tipos': typeof AuthenticatedAtividadesTiposRoute
  '/atividades': typeof AuthenticatedAtividadesIndexRoute
  '/atividades/projeto/$id': typeof AuthenticatedAtividadesProjetoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/acoes': typeof AuthenticatedAcoesRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRouteWithChildren
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/ciclo': typeof AuthenticatedCicloRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/funis': typeof AuthenticatedFunisRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/social-selling': typeof AuthenticatedSocialSellingRoute
  '/_authenticated/tempo': typeof AuthenticatedTempoRoute
  '/_authenticated/atividades/agenda': typeof AuthenticatedAtividadesAgendaRoute
  '/_authenticated/atividades/intencoes': typeof AuthenticatedAtividadesIntencoesRoute
  '/_authenticated/atividades/semanas': typeof AuthenticatedAtividadesSemanasRoute
  '/_authenticated/atividades/tipos': typeof AuthenticatedAtividadesTiposRoute
  '/_authenticated/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/_authenticated/atividades/projeto/$id': typeof AuthenticatedAtividadesProjetoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/acoes'
    | '/atividades'
    | '/calendario'
    | '/ciclo'
    | '/conteudo'
    | '/crm'
    | '/dashboard'
    | '/faturamento'
    | '/funis'
    | '/perfil'
    | '/social-selling'
    | '/tempo'
    | '/atividades/agenda'
    | '/atividades/intencoes'
    | '/atividades/semanas'
    | '/atividades/tipos'
    | '/atividades/'
    | '/atividades/projeto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/acoes'
    | '/calendario'
    | '/ciclo'
    | '/conteudo'
    | '/crm'
    | '/dashboard'
    | '/faturamento'
    | '/funis'
    | '/perfil'
    | '/social-selling'
    | '/tempo'
    | '/atividades/agenda'
    | '/atividades/intencoes'
    | '/atividades/semanas'
    | '/atividades/tipos'
    | '/atividades'
    | '/atividades/projeto/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/acoes'
    | '/_authenticated/atividades'
    | '/_authenticated/calendario'
    | '/_authenticated/ciclo'
    | '/_authenticated/conteudo'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/faturamento'
    | '/_authenticated/funis'
    | '/_authenticated/perfil'
    | '/_authenticated/social-selling'
    | '/_authenticated/tempo'
    | '/_authenticated/atividades/agenda'
    | '/_authenticated/atividades/intencoes'
    | '/_authenticated/atividades/semanas'
    | '/_authenticated/atividades/tipos'
    | '/_authenticated/atividades/'
    | '/_authenticated/atividades/projeto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tempo': {
      id: '/_authenticated/tempo'
      path: '/tempo'
      fullPath: '/tempo'
      preLoaderRoute: typeof AuthenticatedTempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social-selling': {
      id: '/_authenticated/social-selling'
      path: '/social-selling'
      fullPath: '/social-selling'
      preLoaderRoute: typeof AuthenticatedSocialSellingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funis': {
      id: '/_authenticated/funis'
      path: '/funis'
      fullPath: '/funis'
      preLoaderRoute: typeof AuthenticatedFunisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo': {
      id: '/_authenticated/ciclo'
      path: '/ciclo'
      fullPath: '/ciclo'
      preLoaderRoute: typeof AuthenticatedCicloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acoes': {
      id: '/_authenticated/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AuthenticatedAcoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades/': {
      id: '/_authenticated/atividades/'
      path: '/'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AuthenticatedAtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/atividades/tipos': {
      id: '/_authenticated/atividades/tipos'
      path: '/tipos'
      fullPath: '/atividades/tipos'
      preLoaderRoute: typeof AuthenticatedAtividadesTiposRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/atividades/semanas': {
      id: '/_authenticated/atividades/semanas'
      path: '/semanas'
      fullPath: '/atividades/semanas'
      preLoaderRoute: typeof AuthenticatedAtividadesSemanasRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/atividades/intencoes': {
      id: '/_authenticated/atividades/intencoes'
      path: '/intencoes'
      fullPath: '/atividades/intencoes'
      preLoaderRoute: typeof AuthenticatedAtividadesIntencoesRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/atividades/agenda': {
      id: '/_authenticated/atividades/agenda'
      path: '/agenda'
      fullPath: '/atividades/agenda'
      preLoaderRoute: typeof AuthenticatedAtividadesAgendaRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
    '/_authenticated/atividades/projeto/$id': {
      id: '/_authenticated/atividades/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/atividades/projeto/$id'
      preLoaderRoute: typeof AuthenticatedAtividadesProjetoIdRouteImport
      parentRoute: typeof AuthenticatedAtividadesRoute
    }
  }
}

interface AuthenticatedAtividadesRouteChildren {
  AuthenticatedAtividadesAgendaRoute: typeof AuthenticatedAtividadesAgendaRoute
  AuthenticatedAtividadesIntencoesRoute: typeof AuthenticatedAtividadesIntencoesRoute
  AuthenticatedAtividadesSemanasRoute: typeof AuthenticatedAtividadesSemanasRoute
  AuthenticatedAtividadesTiposRoute: typeof AuthenticatedAtividadesTiposRoute
  AuthenticatedAtividadesIndexRoute: typeof AuthenticatedAtividadesIndexRoute
  AuthenticatedAtividadesProjetoIdRoute: typeof AuthenticatedAtividadesProjetoIdRoute
}

const AuthenticatedAtividadesRouteChildren: AuthenticatedAtividadesRouteChildren =
  {
    AuthenticatedAtividadesAgendaRoute: AuthenticatedAtividadesAgendaRoute,
    AuthenticatedAtividadesIntencoesRoute:
      AuthenticatedAtividadesIntencoesRoute,
    AuthenticatedAtividadesSemanasRoute: AuthenticatedAtividadesSemanasRoute,
    AuthenticatedAtividadesTiposRoute: AuthenticatedAtividadesTiposRoute,
    AuthenticatedAtividadesIndexRoute: AuthenticatedAtividadesIndexRoute,
    AuthenticatedAtividadesProjetoIdRoute:
      AuthenticatedAtividadesProjetoIdRoute,
  }

const AuthenticatedAtividadesRouteWithChildren =
  AuthenticatedAtividadesRoute._addFileChildren(
    AuthenticatedAtividadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcoesRoute: typeof AuthenticatedAcoesRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRouteWithChildren
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCicloRoute: typeof AuthenticatedCicloRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedFunisRoute: typeof AuthenticatedFunisRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSocialSellingRoute: typeof AuthenticatedSocialSellingRoute
  AuthenticatedTempoRoute: typeof AuthenticatedTempoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcoesRoute: AuthenticatedAcoesRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRouteWithChildren,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCicloRoute: AuthenticatedCicloRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedFunisRoute: AuthenticatedFunisRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSocialSellingRoute: AuthenticatedSocialSellingRoute,
  AuthenticatedTempoRoute: AuthenticatedTempoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
