/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTempoRouteImport } from './routes/_authenticated/tempo'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedSocialSellingRouteImport } from './routes/_authenticated/social-selling'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedObjetivosRouteImport } from './routes/_authenticated/objetivos'
import { Route as AuthenticatedFunisRouteImport } from './routes/_authenticated/funis'
import { Route as AuthenticatedFollowUpRouteImport } from './routes/_authenticated/follow-up'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedCicloRouteImport } from './routes/_authenticated/ciclo'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAcoesRouteImport } from './routes/_authenticated/acoes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTempoRoute = AuthenticatedTempoRouteImport.update({
  id: '/tempo',
  path: '/tempo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialSellingRoute =
  AuthenticatedSocialSellingRouteImport.update({
    id: '/social-selling',
    path: '/social-selling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObjetivosRoute = AuthenticatedObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunisRoute = AuthenticatedFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpRoute = AuthenticatedFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCicloRoute = AuthenticatedCicloRouteImport.update({
  id: '/ciclo',
  path: '/ciclo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcoesRoute = AuthenticatedAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo': typeof AuthenticatedCicloRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/objetivos': typeof AuthenticatedObjetivosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social-selling': typeof AuthenticatedSocialSellingRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/tempo': typeof AuthenticatedTempoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo': typeof AuthenticatedCicloRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/objetivos': typeof AuthenticatedObjetivosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social-selling': typeof AuthenticatedSocialSellingRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/tempo': typeof AuthenticatedTempoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/acoes': typeof AuthenticatedAcoesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/ciclo': typeof AuthenticatedCicloRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/follow-up': typeof AuthenticatedFollowUpRoute
  '/_authenticated/funis': typeof AuthenticatedFunisRoute
  '/_authenticated/objetivos': typeof AuthenticatedObjetivosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/social-selling': typeof AuthenticatedSocialSellingRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/tempo': typeof AuthenticatedTempoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/acoes'
    | '/calendario'
    | '/ciclo'
    | '/conteudo'
    | '/crm'
    | '/dashboard'
    | '/faturamento'
    | '/follow-up'
    | '/funis'
    | '/objetivos'
    | '/perfil'
    | '/social-selling'
    | '/tarefas'
    | '/tempo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/acoes'
    | '/calendario'
    | '/ciclo'
    | '/conteudo'
    | '/crm'
    | '/dashboard'
    | '/faturamento'
    | '/follow-up'
    | '/funis'
    | '/objetivos'
    | '/perfil'
    | '/social-selling'
    | '/tarefas'
    | '/tempo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/acoes'
    | '/_authenticated/calendario'
    | '/_authenticated/ciclo'
    | '/_authenticated/conteudo'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/faturamento'
    | '/_authenticated/follow-up'
    | '/_authenticated/funis'
    | '/_authenticated/objetivos'
    | '/_authenticated/perfil'
    | '/_authenticated/social-selling'
    | '/_authenticated/tarefas'
    | '/_authenticated/tempo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tempo': {
      id: '/_authenticated/tempo'
      path: '/tempo'
      fullPath: '/tempo'
      preLoaderRoute: typeof AuthenticatedTempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social-selling': {
      id: '/_authenticated/social-selling'
      path: '/social-selling'
      fullPath: '/social-selling'
      preLoaderRoute: typeof AuthenticatedSocialSellingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objetivos': {
      id: '/_authenticated/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof AuthenticatedObjetivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funis': {
      id: '/_authenticated/funis'
      path: '/funis'
      fullPath: '/funis'
      preLoaderRoute: typeof AuthenticatedFunisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-up': {
      id: '/_authenticated/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AuthenticatedFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo': {
      id: '/_authenticated/ciclo'
      path: '/ciclo'
      fullPath: '/ciclo'
      preLoaderRoute: typeof AuthenticatedCicloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acoes': {
      id: '/_authenticated/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AuthenticatedAcoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcoesRoute: typeof AuthenticatedAcoesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCicloRoute: typeof AuthenticatedCicloRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedFollowUpRoute: typeof AuthenticatedFollowUpRoute
  AuthenticatedFunisRoute: typeof AuthenticatedFunisRoute
  AuthenticatedObjetivosRoute: typeof AuthenticatedObjetivosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSocialSellingRoute: typeof AuthenticatedSocialSellingRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedTempoRoute: typeof AuthenticatedTempoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcoesRoute: AuthenticatedAcoesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCicloRoute: AuthenticatedCicloRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedFollowUpRoute: AuthenticatedFollowUpRoute,
  AuthenticatedFunisRoute: AuthenticatedFunisRoute,
  AuthenticatedObjetivosRoute: AuthenticatedObjetivosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSocialSellingRoute: AuthenticatedSocialSellingRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedTempoRoute: AuthenticatedTempoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
